# Generated by Django 4.1.3 on 2023-01-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='day',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='time',
        ),
    ]
