# Generated by Django 4.1.3 on 2022-11-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdata',
            name='title',
        ),
    ]
