# Generated by Django 4.1.3 on 2022-11-29 09:08

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0002_remove_contactdata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='message',
            field=mdeditor.fields.MDTextField(default='', verbose_name='お知らせ内容'),
        ),
    ]
