# Generated by Django 4.1.3 on 2023-01-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0002_shiftdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdatamodel',
            name='current_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='現在の勤務時間'),
        ),
        migrations.AlterField(
            model_name='shiftdatamodel',
            name='current_day',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='現在の曜日シフト'),
        ),
    ]
