# Generated by Django 4.1.3 on 2023-01-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0003_shiftdatamodel_current_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdatamodel',
            name='user_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='UserID'),
        ),
        migrations.AlterField(
            model_name='shiftdatamodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
