# Generated by Django 4.1.3 on 2022-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0003_alter_contactdata_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='tag',
            field=models.CharField(max_length=20, null=True, verbose_name='タグ'),
        ),
    ]
