# Generated by Django 4.1.3 on 2022-11-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0004_contactdata_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='choice_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='お知らせ対象者'),
        ),
    ]
