# Generated by Django 4.1.3 on 2022-12-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0006_remove_notice_choice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='overtime',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='休出勤務時間'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='tag',
            field=models.CharField(blank=True, choices=[('追加出勤', '追加出勤'), ('協力休暇', '協力休暇'), ('追加出勤 + 協力休暇', '追加出勤 + 協力休暇'), ('その他', 'その他')], max_length=20, null=True, verbose_name='タグ'),
        ),
    ]
