# Generated by Django 4.1.3 on 2022-12-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0007_applylist_overtime_alter_notice_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applydata',
            name='holiday_date',
        ),
        migrations.RemoveField(
            model_name='applydata',
            name='work_date',
        ),
    ]
