# Generated by Django 4.1.3 on 2022-12-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solu_t', '0008_remove_applydata_holiday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='shift',
            field=models.CharField(choices=[('日勤', '日勤'), ('夜勤', '夜勤'), ('全体', '全体')], max_length=5, verbose_name='勤務シフト'),
        ),
    ]
